project: audio-mnist
# name: baseline-1

seed_everything: 42

model:
  class_path: BaseLine
  init_args:
    net:
      class_path: Cifar10Resnet18
      init_args:
        num_classes: 10
    loss_module:
      class_path: CrossEntropyLoss

trainer:
  accelerator: gpu
  precision: 16-mixed
  n_epoch: 8
  check_val_every_n_epoch: 1
  plugins:
    - AsyncCheckpointIO

optimizer:
  class_path: SGD
  init_args:
    lr: 0.2
    momentum: 0.9
    weight_decay: 0.0001

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: 20

data:
  class_path:
  init_args:
    root: data
    batch_size: 128
    val_split: 0.2
    num_worker: 4
  dataset:
    init_args:
      audio_max_ms: 1000
  mel_spectrogram:
    sample_rate: 16000 # it will resample the audio into this value
    n_fft: 512 # n_fft >= win_length. recommend value of 2^n for computation speed
    win_length: 400 # default 25ms in linguistics field 
    hop_length: 160 # default 10ms
    n_mels: 40
    f_min: 25
    f_max: 7500
    pad: 0
  mfcc:
    something:
  transform: