project: dacon-emotion

seed_everything: 42

model:
  class_path: BaseLine
  HFAutoClassifier:
    init_args:
      model_name: facebook/wav2vec2-base      
  BaseLine:
    init_args:
      arg:
  num_classes: 6
  loss_module:
    class_path: CrossEntropyLoss

trainer:
  accelerator: gpu
  precision: 16-mixed
  n_epoch: 50
  check_val_every_n_epoch: 1
  lr: 0.2
  plugins:
    - AsyncCheckpointIO

optimizer:
  class_path: SGD
  init_args:
    momentum: 0.9
    weight_decay: 0.0001

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: 20

data:
  class_path:
  init_args:
    root: data
    batch_size: 128
    val_split: 0.2
    num_worker: 3
  dataset:
    init_args:

transform:
  class_path: CustomTransform
  Wav2Vec2Extractor:
    init_args:
      model_name: facebook/wav2vec2-base
      sample_rate: 16000
      audio_max_ms: 1000

  CustomTransform:
    init_args:
      audio_max_ms: 1000
      sample_rate: 16000 # for resampling
      mel_spectrogram:
        n_fft: 512 # n_fft >= win_length. recommend value of 2^n for computation speed
        win_length: 400 # default 25ms in linguistics field 
        hop_length: 160 # default 10ms
        n_mels: 40
        f_min: 25
        f_max: 7500
        pad: 0
      mfcc:
        something:
      time_shift: 
        use: !!bool False
        shift_max: !!float 0.4
      masking: 
        use: !!bool False
        max_mask_percent: !!float 0.1
        n_freq_mask: 1
        n_time_mask: 1
      noising: 
        use: !!bool False
        noise_level: !!float 0.01