wandb_version: 1

project:
  desc: null
  value: audio-mnist
name:
  desc: null
  value: baseline-1
seed_everything:
  desc: null
  value: 42
model:
  desc: null
  value:
    class_path: BaseLine
    init_args:
      net:
        class_path: Cifar10Resnet18
        init_args:
          num_classes: 10
      loss_module:
        class_path: CrossEntropyLoss
trainer:
  desc: null
  value:
    accelerator: gpu
    precision: 16-mixed
    n_epoch: 3
    check_val_every_n_epoch: 1
    plugins:
    - AsyncCheckpointIO
optimizer:
  desc: null
  value:
    class_path: SGD
    init_args:
      lr: 0.2
      momentum: 0.9
      weight_decay: 0.0001
lr_scheduler:
  desc: null
  value:
    class_path: CosineAnnealingLR
data:
  desc: null
  value:
    class_path: null
    init_args:
      root: data
      batch_size: 128
      val_split: 0.2
      num_worker: 3
    dataset:
      init_args:
        audio_max_ms: 1000
    mel_spectrogram:
      sample_rate: 16000
      n_fft: 512
      win_length: 400
      hop_length: 160
      n_mels: 40
      f_min: 25
      f_max: 7500
      pad: 0
    mfcc:
      something: null
    transform: null
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700748878.201235
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 7
      - 13
      - 16
      - 23
      4: 3.10.6
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: val/acc
      5: 1
      6:
      - 1
